### ISSUE TITLE
Tracks (in a playlist) are sometimes null, parsing exception is thrown

### ISSUE THREAD

**Issue by molikuner** [adamint/spotify-web-api-kotlin#127]
**Describe the bug**
Recently I found some playlists with an extra track which is null. As this is against the docs, I would not allow the library to parse this, but feel free to start a discussion about it.
Current example (may get invalid in future, as this is a public playlist...): `https://api.spotify.com/v1/playlists/37i9dQZF1DXc5e2bJhV6pu` -> `track` was null at `response.tracks.items[50].track`

Error thrown by library:
```
com.adamratzman.spotify.SpotifyException: Unable to parse {
  "collaborative" : false,
  "description" : "Get your day off to a cracking start!",
  "external_urls" : {
    "spotify" : "https://open.spotify.com/playlist/37i9dQZF1DXc5e2bJhV6pu"
  },
  "followers" : {
    "href" : null,
    "total" : 615993
  },
  "href" : "https://api.spotify.com/v1/playlists/37i9dQZF1DXc5e2bJhV6pu",
  "id" : "37i9dQZF1DXc5e2bJhV6pu",
  "images" : [ {
    "height" : null,
    "url" : "https://pl.scdn.co/images/pl/default/3297e1b50ff1c49e88c28eb07627a98d1cbb3bbb",
    "width" : null
  } ],
  "name" : "Morning Motivation",
  "owner" : {
    "display_name" : "Spotify",
    "external_urls" : {
      "spotify" : "https://open.spotify.com/user/spotify"
    },
    "href" : "https://api.spotify.com/v1/users/spotify",
    "id" : "spotify",
    "type" : "user",
    "uri" : "spotify:user:spotify"
  },
  "primary_color" : null,
  "public" : false,
  "snapshot_id" : "MTU2Njk0OTM4MCwwMDAwMDAwMDAyZDNkZDhlZmZkZmQ5MjUxMWFlOWM4NWNlZWMxYjU2",
  "tracks" : {
    "href" : "https://api.spotify.com/v1/playlists/37i9dQZF1DXc5e2bJhV6pu/tracks?offset=0&limit=100",
    "items" : [ ** removed to shorten the log, but here were absolutly fine track objects **, {
      "added_at" : "2019-08-22T23:17:32Z",
      "added_by" : {
        "external_urls" : {
          "spotify" : "https://open.spotify.com/user/"
        },
        "href" : "https://api.spotify.com/v1/users/",
        "id" : "",
        "type" : "user",
        "uri" : "spotify:user:"
      },
      "is_local" : false,
      "primary_color" : null,
      "track" : null,
      "video_thumbnail" : {
        "url" : null
      }
    }, ** removed to shorten the log, but here were absolutly fine track objects ** ],
    "limit" : 100,
    "next" : null,
    "offset" : 0,
    "previous" : null,
    "total" : 60
  },
  "type" : "playlist",
  "uri" : "spotify:playlist:37i9dQZF1DXc5e2bJhV6pu"
}
	at com.adamratzman.spotify.endpoints.public.PlaylistAPI$getPlaylist$1$1.invoke(PlaylistAPI.kt:140)
	at com.adamratzman.spotify.endpoints.public.PlaylistAPI$getPlaylist$1$1.invoke(PlaylistAPI.kt:29)
	at com.adamratzman.spotify.utils.MiscUtilsKt.catch(MiscUtils.kt:11)
	at com.adamratzman.spotify.endpoints.public.PlaylistAPI$getPlaylist$1.get(PlaylistAPI.kt:76)
	at com.adamratzman.spotify.endpoints.public.PlaylistAPI$getPlaylist$1.get(PlaylistAPI.kt:29)
	at com.adamratzman.spotify.SpotifyRestAction.complete(SpotifyRestAction.kt:34)
	at com.adamratzman.spotify.SpotifyRestAction$queue$3.run(SpotifyRestAction.kt:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.squareup.moshi.JsonDataException: Non-null value 'track' was null at $.tracks.items[50].track
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:86)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:83)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:83)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:41)
	at com.adamratzman.spotify.endpoints.public.PlaylistAPI$getPlaylist$1$1.invoke(PlaylistAPI.kt:132)
	... 13 more
```

**To Reproduce**
Well, hard to say, because there is no bug in this library, but one in the Spotify Web API. You can use the PlaylistAPI.getPlaylistTracks endpoint of playlist `spotify:playlist:37i9dQZF1DXc5e2bJhV6pu` currently. But this may change in future...

**Expected behavior**
Not shure, but I'm okay with the current behaviour. I'm just opening this issue, to make other users of the library aware of it. For me it's a `wontfix` issue... Should be fixed by Spotify.

See spotify/web-api#958 for current information.

**Comment by adamint** [comment]
Weird. Good to know. We should probably catch this after deserializing the response.

**Comment by adamint** [comment]
Decided to simply document that this behavior is unlikely, but since it's against Spotify documentation, I agree that we shouldn't alter the library to account for it.

**Comment by aymather** [comment]
I ran into this same issue while using the SpotiPy api, you can read our discussion as to why this behavior happens.

https://github.com/plamere/spotipy/issues/626

**Comment by adamint** [comment]
Thank you @aymather, that was insightful!
