### ISSUE TITLE
Cannot build SpotifyClientAPI with expired token

### ISSUE THREAD

**Issue by d-eder** [adamint/spotify-web-api-kotlin#151]
**Description**
If you create an instance with an expired token an exception gets thrown in the init method. This should not be, because you aren't even able to refresh your access token with a valid refresh token. 
This is because the user profile get loaded in the init function, which throws the exception.

**To Reproduce**
Build an instance of the SpotifyClientAPI with an expired token.

**Stack**
``` 
com.adamratzman.spotify.models.BadRequestException: Received Status Code 401. Error cause: Invalid access token
	at com.adamratzman.spotify.http.SpotifyEndpoint.handleResponse(Endpoints.kt:110) ~[spotify-api-kotlin-2.3.08.jar:na]
	at com.adamratzman.spotify.http.SpotifyEndpoint.execute(Endpoints.kt:70) ~[spotify-api-kotlin-2.3.08.jar:na]
	at com.adamratzman.spotify.http.SpotifyEndpoint.execute$default(Endpoints.kt:49) ~[spotify-api-kotlin-2.3.08.jar:na]
	at com.adamratzman.spotify.http.SpotifyEndpoint.get$spotify_api_kotlin(Endpoints.kt:25) ~[spotify-api-kotlin-2.3.08.jar:na]
	at com.adamratzman.spotify.endpoints.client.ClientUserAPI$getUserProfile$1.get(ClientUserAPI.kt:29) ~[spotify-api-kotlin-2.3.08.jar:na]
	at com.adamratzman.spotify.endpoints.client.ClientUserAPI$getUserProfile$1.get(ClientUserAPI.kt:16) ~[spotify-api-kotlin-2.3.08.jar:na]
	at com.adamratzman.spotify.SpotifyRestAction.complete(SpotifyRestAction.kt:34) ~[spotify-api-kotlin-2.3.08.jar:na]
	at com.adamratzman.spotify.SpotifyClientAPI.<init>(SpotifyAPI.kt:354) ~[spotify-api-kotlin-2.3.08.jar:na]
	at com.adamratzman.spotify.SpotifyApiBuilderDsl.buildClient(Builder.kt:460) ~[spotify-api-kotlin-2.3.08.jar:na]
	at com.adamratzman.spotify.SpotifyApiBuilderDsl.buildClient(Builder.kt:400) ~[spotify-api-kotlin-2.3.08.jar:na]
```

**Comment by adamint** [comment]
This was intended behavior simply because I didn’t think of this use case, but we’ll change that before releasing v3.0.0-rc.3. I’m currently targeting that release candidate for Sunday 11/10.

**Comment by adamint** [comment]
Thank you for bringing this to our attention.
