### ISSUE TITLE
Decoding issue when working with local files

### ISSUE THREAD

**Issue by Nielssg** [adamint/spotify-web-api-kotlin#187]
**Describe the bug**
When I try to get a playlist, the library crashes with a JSON Decode exception telling me that ` Invalid JSON at 1373: Expected string or non-null literal`. It happened in a large playlist, so I tried to get an as small as possible dataset to work with, which eventually led to the discovery that it was because of a local file.

**To Reproduce**
Have a playlist with a local file from someone else. When you try to get the playlist, it will crash telling you that it expected a not-null literal or string.

```Kotlin
val spotifyId = "SOME_PLAYLIST_ID"
spotifyClientAPI?.playlists?.getPlaylist(spotifyId)?.queue { playlist ->
   // Got the playlist
}
```

**Expected behavior**
It would be awesome if the library would also accept local files, or at least can handle it without decoding issues.

**Screenshots**
I have the JSON of a normal response from the getPlaylist call (left) and a response with a local file in the tracks. I stripped all data that existed on both sides to get a clear understanding of the differences.

### JSON Differences 
![image](https://user-images.githubusercontent.com/20494853/73104482-bf43f400-3ef6-11ea-897a-e70613cc9277.png)

### Log
```
com.adamratzman.spotify.SpotifyException$ParseException: Unable to parse {
        // HERE IS THE JSON OF THE REQUEST, WHICH HAS BEEN STRIPPED DOWN AS SEEN IN THE IMAGE
      }
        at com.adamratzman.spotify.models.serialization.SerializationUtilsKt.parseJson(SerializationUtils.kt:190)
        at com.adamratzman.spotify.endpoints.public.PlaylistApi$getPlaylist$1.invokeSuspend(PlaylistApi.kt:152)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:216)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:172)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:216)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:172)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:216)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:172)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
     Caused by: kotlinx.serialization.json.JsonDecodingException: Invalid JSON at 1373: Expected string or non-null literal
        at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:293)
        at kotlinx.serialization.json.internal.JsonReader.takeString(JsonReader.kt:142)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeString(StreamingJsonInput.kt:154)
        at kotlinx.serialization.ElementValueDecoder.decodeStringElement(ElementWise.kt:128)
        at com.adamratzman.spotify.models.SimpleAlbum$$serializer.deserialize(Unknown Source:177)
        at com.adamratzman.spotify.models.SimpleAlbum$$serializer.deserialize(Albums.kt:34)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
        at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:131)
        at com.adamratzman.spotify.models.Track$$serializer.deserialize(Unknown Source:427)
        at com.adamratzman.spotify.models.Track$$serializer.deserialize(Track.kt:112)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeNullableSerializableValue(Coders.kt:103)
        at kotlinx.serialization.json.JsonInput$DefaultImpls.decodeNullableSerializableValue(Unknown Source:8)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeNullableSerializableValue(StreamingJsonInput.kt:16)
        at kotlinx.serialization.ElementValueDecoder.decodeNullableSerializableElement(ElementWise.kt:133)
        at com.adamratzman.spotify.models.PlaylistTrack$$serializer.deserialize(Unknown Source:161)
        at com.adamratzman.spotify.models.PlaylistTrack$$serializer.deserialize(Playlist.kt:75)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
        at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:131)
        at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:89)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:58)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:39)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:49)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
        at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:131)
        at com.adamratzman.spotify.models.PagingObject$$serializer.deserialize(Unknown Source:91)
        at com.adamratzman.spotify.models.PagingObject$$serializer.deserialize(PagingObjects.kt:65)
E/AndroidRuntime:     at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
        at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:131)
        at com.adamratzman.spotify.models.Playlist$$serializer.deserialize(Unknown Source:547)
        at com.adamratzman.spotify.models.Playlist$$serializer.deserialize(Playlist.kt:107)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
        at kotlinx.serialization.CoreKt.decode(Core.kt:80)
        at kotlinx.serialization.json.Json.parse(Json.kt:126)
        at com.adamratzman.spotify.models.serialization.SerializationUtilsKt$toObject$1.invoke(SerializationUtils.kt:33)
        at com.adamratzman.spotify.models.serialization.SerializationUtilsKt$toObject$1.invoke(Unknown Source:2)
        at com.adamratzman.spotify.models.serialization.SerializationUtilsKt.parseJson(SerializationUtils.kt:188)
        	... 22 more
```

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest

**Smartphone:**
 - Device: Samsung Galaxy S10
 - OS: Android 10
 - Browser: Chrome
 - Version: Latest

**Additional context**
Library version: 3.0.01

**Comment by adamint** [comment]
Right. This was something I hadn’t thought of. Great catch. I need to think about how best to resolve this.

**Comment by Nielssg** [comment]
Yeah totally understand that you didn't think of this, I wouldn't have thought of it either!

**Comment by adamint** [comment]
The correct solution will be for us to implement JsonParametricSerializer on `Playable` objects

See the following example for selecting a serializer based on the known local track uri format

```kotlin
@Serializable
data class ParentObject(@Serializable(with = TransformerSerializer::class) val poly: Poly)

@Serializable
@SerialName("track")
data class Poly1(val a: Int, override val id: String, override val uri: String, override val type: String) : Poly()

@Serializable
@SerialName("local")
data class Poly2(val b: String, override val id: String, override val uri: String, override val type: String) : Poly() {
}

@Serializable
sealed class Poly {
    abstract val id: String
    abstract val uri: String
    abstract val type:String
}

object TransformerSerializer : JsonParametricSerializer<Poly>(Poly::class) {
    override fun selectSerializer(element: JsonElement): KSerializer<out Poly> {
        element as JsonObject
        return when{
            element["uri"]?.contentOrNull?.matches("spotify:local:.+".toRegex()) == true -> Poly2.serializer()
            else -> Poly1.serializer()
        }
    }
}


val json = Json(
    JsonConfiguration.Stable.copy(isLenient = true)
)

fun main() {
    println(json.parse(ParentObject.serializer(), """{poly: {"type": "track", "b": "4", "id": "test", "uri": "spotify:local:David+Wise:Donkey+Kong+Country%3A+Tropical+Freeze:Snomads+Island:127"}}"""))
}
```
