### ISSUE TITLE
java.lang.NoClassDefFoundError: java.util.Base64

### ISSUE THREAD

**Issue by Zevsus** [adamint/spotify-web-api-kotlin#193]
It works only from Android 8 inclusive. The library is the latest version of kotlin ext.kotlin_version = '1.3.72'.
at com.adamratzman.spotify.http.EndpointsKt.base64ByteEncode(Endpoints.kt:9)
        at com.adamratzman.spotify.SpotifyApiKt.executeTokenRequest(SpotifyApi.kt:717)
        at com.adamratzman.spotify.SpotifyApi$Companion.getCredentialedToken(SpotifyApi.kt:246)
        at com.adamratzman.spotify.SpotifyAppApiBuilder.suspendBuild(Builder.kt:494)
        at com.adamratzman.spotify.ISpotifyApiBuilder$build$$inlined$runBlocking$1.invokeSuspend(Concurrency.kt:33)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:271)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at com.adamratzman.spotify.ISpotifyApiBuilder$DefaultImpls.build(Builder.kt:667)
        at com.adamratzman.spotify.ISpotifyAppApiBuilder$DefaultImpls.build(Builder.kt)
        at com.adamratzman.spotify.SpotifyAppApiBuilder.build(Builder.kt:427)
        at com.adamratzman.spotify.SpotifyAppApiBuilder.build(Builder.kt:427)

open class Spotify {
    private var api: SpotifyAppApi? = null

    fun get(clintId:String, secret: String ): SpotifyAppApi? {
        if (api == null){
            try {
                api = spotifyAppApi(clintId,secret ).build()
            }catch (e : Exception){
                Crashlytics.logException(e)
                return api

            }
        }
        return api as SpotifyAppApi
    }

}

                try {
                    spotApi = new Spotify().get(getString(R.string.clienid),getString(R.string.secretid));
                }catch (Exception ignored){}

**Comment by molikuner** [comment]
Looks like `java.util.Base64` is a Java 8 class, and that's available since Java 7 (I think).
We should try to replace it with something more available class:
https://stackoverflow.com/questions/14413169/which-java-library-provides-base64-encoding-decoding

**Comment by adamint** [comment]
Hmm, this is a fun problem. I'll implement one of the solutions in the SO answer @Zevsus
