### ISSUE TITLE
AuthenticationException

### ISSUE THREAD

**Issue by Zevsus** [adamint/spotify-web-api-kotlin#209]
Hi pls change spotify-web-api-kotlin/src/jvmMain/kotlin/com/adamratzman/spotify/http/Endpoints.kt Replace java.util.Base64 with android.util.Base64.

**Comment by adamint** [comment]
Hi, thanks for opening this issue.
Please use the `spotify-api-kotlin-android` artifact instead of `spotify-api-kotlin`. `spotify-api-kotlin` targets Kotlin/JVM, which `spotify-api-kotlin-android` targets Kotlin/Android.
Since the JRE does not contain Android classes, what you are asking for is sadly not possible.

So please instead use this:
```
implementation 'com.adamratzman:spotify-api-kotlin-android:3.2.01'
```

With 3.2.01 (not 3.2.02, which is currently being released), you will also need to add the following to your android/buildTypes closures (such as release):
```
            matchingFallbacks = ['release', 'debug']
```

**However, once 3.2.02 is synced to maven central, you will not need to use matching fallbacks.**

```
implementation 'com.adamratzman:spotify-api-kotlin-android:3.2.02'
```

To successfully build, you might need to exclude kotlin_modules from the packaging. To do this, inside the android/buildTypes/release closure, you would put:
```
 packagingOptions {
                exclude 'META-INF/*.kotlin_module'
            }
```

**Comment by adamint** [comment]
Could you confirm your problem is fixed @Zevsus?

**Comment by Zevsus** [comment]
Thanks for the work done and the quick response!

**Comment by Zevsus** [comment]
If before everything loaded normally, now this error AuthenticationException Invalid credentials provided in the login process.
                api = spotifyAppApi(clintId,secret).build()
            }catch (e : Exception){
                Log.d("KJKJKJ", e.toString())
                FirebaseCrashlytics.getInstance().recordException(e)
                return api
            }

**Comment by adamint** [comment]
Do you have a full stack trace? And which API versions have you tried this with?

**Comment by Zevsus** [comment]
Hi. Api 16 - 30 (Android Studio Emulators).
     Caused by: com.adamratzman.spotify.SpotifyException$AuthenticationException: Invalid credentials provided in the login process (clientId=________, clientSecret=______)
        at com.adamratzman.spotify.SpotifyAppApiBuilder.suspendBuild(Builder.kt:955)
        at com.adamratzman.spotify.ISpotifyApiBuilder$build$$inlined$runBlocking$1.invokeSuspend(Concurrency.kt:33)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
        at com.adamratzman.spotify.ISpotifyApiBuilder$DefaultImpls.build(Builder.kt:1118)
        at com.adamratzman.spotify.ISpotifyAppApiBuilder$DefaultImpls.build(Unknown Source:3)
        at com.adamratzman.spotify.SpotifyAppApiBuilder.build(Builder.kt:865)
        at com.adamratzman.spotify.SpotifyAppApiBuilder.build(Builder.kt:865)
        at _______.online.utils.Spotify.get(Spotify.kt:15)

**Comment by adamint** [comment]
Are you sure that's the full stack trace? There should be nested exceptions

**Comment by Zevsus** [comment]
2020-08-07 20:34:15.527 5965-5965/____.online E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ____.online.online:musicplayer, PID: 5965
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
     Caused by: com.adamratzman.spotify.SpotifyException$AuthenticationException: Invalid credentials provided in the login process (clientId=cc4ec3b3efc8494fad531d5547bf6550, clientSecret=3692f178f3cc4e5ebb45227b3eccb770)
        at com.adamratzman.spotify.SpotifyAppApiBuilder.suspendBuild(Builder.kt:955)
        at com.adamratzman.spotify.ISpotifyApiBuilder$build$$inlined$runBlocking$1.invokeSuspend(Concurrency.kt:33)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at com.adamratzman.spotify.ISpotifyApiBuilder$DefaultImpls.build(Builder.kt:1118)
        at com.adamratzman.spotify.ISpotifyAppApiBuilder$DefaultImpls.build(Builder.kt)
        at com.adamratzman.spotify.SpotifyAppApiBuilder.build(Builder.kt:865)
        at com.adamratzman.spotify.SpotifyAppApiBuilder.build(Builder.kt:865)

**Comment by adamint** [comment]
At (clientId=, clientSecret=_____)
Does this mean that clientId is empty?

**Comment by Zevsus** [comment]
This means that I removed them from here.
