### ISSUE TITLE
Retrieving all playlists of the current user causes JsonDecodingException

### ISSUE THREAD

**Issue by Nielssg** [adamint/spotify-web-api-kotlin#229]
**Describe the bug**
When using the `clientPlaylists` call (`spotifyClientAPI.playlists.getClientPlaylists()`) in combination with `.getAllItems()`, it seems that the JSON cannot be decoded. This only seems to happen when retrieving more than 50 playlists.

**To Reproduce**
1. Add more than 50 playlists to your Spotify account
2. Use the `getClientPlaylists()` API call in combination with `.getAllItems()` to retrieve all your playlists
3. It should fail by telling you it can't decode the JSON

**Expected behavior**
Receiving all user's playlists, for now I can get the first 50 without trouble, but after that it won't get any playlist.

**Screenshots**
Error log:

```
com.adamratzman.spotify.SpotifyException$ParseException: Unable to parse {
  "href" : "https://api.spotify.com/v1/users/09k2n3lfgsrjinq164tqkifyb/playlists?offset=50&limit=50",
  "items" : [ {
    "collaborative" : false,
    "description" : "",
    "external_urls" : {
      "spotify" : "https://open.spotify.com/playlist/1zd3HCIb7EvzS5ZkD1JHkc"
    },
    "href" : "https://api.spotify.com/v1/playlists/1zd3HCIb7EvzS5ZkD1JHkc",
    "id" : "1zd3HCIb7EvzS5ZkD1JHkc",
    "images" : [ {
      "height" : 640,
      "url" : "https://i.scdn.co/image/ab67616d0000b27311bb04f55be562c76d8e8ecf",
      "width" : 640
    } ],
    "name" : "Don't Give Up",
    "owner" : {
      "display_name" : "myapp",
      "external_urls" : {
        "spotify" : "https://open.spotify.com/user/09k2n3lfgsrjinq164tqkifyb"
      },
      "href" : "https://api.spotify.com/v1/users/09k2n3lfgsrjinq164tqkifyb",
      "id" : "09k2n3lfgsrjinq164tqkifyb",
      "type" : "user",
      "uri" : "spotify:user:09k2n3lfgsrjinq164tqkifyb"
    },
    "primary_color" : null,
    "public" : false,
    "snapshot_id" : "MiwzMTljY2I5YTZhODU3MjY1N2UwMjcwOTc3ZmFlMDAyZTM2ZGVkMjhl",
    "tracks" : {
      "href" : "https://api.spotify.com/v1/playlists/1zd3HCIb7EvzS5ZkD1JHkc/tracks",
      "total" : 1
    },
    "type" : "playlist",
    "uri" : "spotify:playlist:1zd3HCIb7EvzS5ZkD1JHkc"
  }, {
    "collaborative" : false,
    "description" : "",
    "external_urls" : {
      "spotify" : "https://open.spotify.com/playlist/39WGXlIQL7qhOmqyLCHFVj"
    },
    "href" : "https://api.spotify.com/v1/playlists/39WGXlIQL7qhOmqyLCHFVj",
    "id" : "39WGXlIQL7qhOmqyLCHFVj",
    "images" : [ {
      "height" : 640,
      "url" : "https://i.scdn.co/image/ab67616d0000b273edc27582d8f5c3a7c56893bf",
      "width" : 640
    } ],
    "name" : "Right Here Waiting",
    "owner" : {
      "display_name" : "myapp",
      "external_urls" : {
        "spotify" : "https://open.spotify.com/user/09k2n3lfgsrjinq164tqkifyb"
      },
      "href" : "https://api.spotify.com/v1/users/09k2n3lfgsrjinq164tqkifyb",
      "id" : "09k2n3lfgsrjinq164tqkifyb",
      "type" : "user",
      "uri" : "spotify:user:09k2n3lfgsrjinq164tqkifyb"
    },
    "primary_color" : null,
    "public" : false,
    "snapshot_id" : "MixkZjVjYjc3NTBhZTdjOTJmMTcyMGFhOWRiZWEyNTk4NWIzYWU0ZmZi",
    "tracks" : {
      "href" : "https://api.spotify.com/v1/playlists/39WGXlIQL7qhOmqyLCHFVj/tracks",
      "total" : 1
    },
    "type" : "playlist",
    "uri" : "spotify:playlist:39WGXlIQL7qhOmqyLCHFVj"
  }, {
    "collaborative" : false,
    "description" : "",
    "external_urls" : {
      "spotify" : "https://open.spotify.com/playlist/0RiKL1FLSnrt1ZkUqFdiNQ"
    },
    "href" : "https://api.spotify.com/v1/playlists/0RiKL1FLSnrt1ZkUqFdiNQ",
    "id" : "0RiKL1FLSnrt1ZkUqFdiNQ",
    "images" : [ {
      "height" : 640,
      "url" : "https://i.scdn.co/image/ab67616d0000b273cc57e9b00b87dd0f6e868347",
      "width" : 640
    } ],
    "name" : "Where Do Broken Hearts Go",
    "owner" : {
      "display_name" : "myapp",
      "external_urls" : {
        "spotify" : "https://open.spotify.com/user/09k2n3lfgsrjinq164tqkifyb"
      },
      "href" : "https://api.spotify.com/v1/users/09k2n3lfgsrjinq164tqkifyb",
      "id" : "09k2n3lfgsrjinq164tqkifyb",
      "type" : "user",
      "uri" : "spotify:user:09k2n3lfgsrjinq164tqkifyb"
    },
    "primary_color" : null,
    "public" : false,
    "snapshot_id" : "MixhMWNiNTQ4YzBjOTgyMWY2ZDA3NjBiMzg2ZDI4ZDE4ZjM4MmEzZTMz",
    "tracks" : {
      "href" : "https://api.spotify.com/v1/playlists/0RiKL1FLSnrt1ZkUqFdiNQ/tracks",
      "total" : 1
    },
    "type" : "playlist",
    "uri" : "spotify:playlist:0RiKL1FLSnrt1ZkUqFdiNQ"
  }, {
    "collaborative" : false,
    "description" : "",
    "external_urls" : {
      "spotify" : "https://open.spotify.com/playlist/4cyi1JBHsmml1DoRY8oTUJ"
    },
    "href" : "https://api.spotify.com/v1/playlists/4cyi1JBHsmml1DoRY8oTUJ",
    "id" : "4cyi1JBHsmml1DoRY8oTUJ",
    "images" : [ {
      "height" : 640,
      "url" : "https://i.scdn.co/image/ab67616d0000b27313018b9c71e6bfc1bdf02d92",
      "width" : 640
    } ],
    "name" : "Breaking Hearts (Ain't What It Used To Be)",
    "owner" : {
      "display_name" : "myapp",
      "external_urls" : {
        "spotify" : "https://open.spotify.com/user/09k2n3lfgsrjinq164tqkifyb"
      },
      "href" : "https://api.spotify.com/v1/users/09k2n3lfgsrjinq164tqkifyb",
      "id" : "09k2n3lfgsrjinq164tqkifyb",
      "type" : "user",
      "uri" : "spotify:user:09k2n3lfgsrjinq164tqkifyb"
    },
    "primary_color" : null,
    "public" : false,
    "snapshot_id" : "MixjNGQ3MDI1YWE2NTExMjRkMzNmYjFhNDNhMDYzNjkwOWEwZDYxM2Jj",
    "tracks" : {
      "href" : "https://api.spotify.com/v1/playlists/4cyi1JBHsmml1DoRY8oTUJ/tracks",
      "total" : 1
    },
    "type" : "playlist",
    "uri" : "spotify:playlist:4cyi1JBHsmml1DoRY8oTUJ"
  }, {
    "collaborative" : false,
    "description" : "",
    "external_urls" : {
      "spotify" : "https://open.spotify.com/playlist/15JNQSdsuQwfs64azeXag4"
    },
    "href" : "https://api.spotify.com/v1/playlists/15JNQSdsuQwfs64azeXag4",
    "id" : "15JNQSdsuQwfs64azeXag4",
    "images" : [ {
      "height" : 640,
      "url" : "https://i.scdn.co/image/ab67616d0000b27342678f54dfd1d5afb3eea19a",
      "width" : 640
    } ],
    "name" : "Slipping Through My Fingers",
    "owner" : {
      "display_name" : "myapp",
      "external_urls" : {
        "spotify" : "https://open.spotify.com/user/09k2n3lfgsrjinq164tqkifyb"
      },
      "href" : "https://api.spotify.com/v1/users/09k2n3lfgsrjinq164tqkifyb",
      "id" : "09k2n3lfgsrjinq164tqkifyb",
      "type" : "user",
      "uri" : "spotify:user:09k2n3lfgsrjinq164tqkifyb"
    },
    "primary_color" : null,
    "public" : false,
    "snapshot_id" : "MixmN2E3NjE5YzljNTA5ZDQ5ODczNmU5YTdjOWU4Y2U0NTA1MjI1ODU2",
    "tracks" : {
      "href" : "https://api.spotify.com/v1/playlists/15JNQSdsuQwfs64azeXag4/tracks",
      "total" : 1
    },
    "type" : "playlist",
    "uri" : "spotify:playlist:15JNQSdsuQwfs64azeXag4"
  }, {
    "collaborative" : false,
    "description" : "",
    "external_urls" : {
      "spotify" : "https://open.spotify.com/playlist/0EKAtuGtWTYrDCT8TfrDVP"
    },
    "href" : "https://api.spotify.com/v1/playlists/0EKAtuGtWTYrDCT8TfrDVP",
    "id" : "0EKAtuGtWTYrDCT8TfrDVP",
    "images" : [ {
      "height" : 640,
      "url" : "https://i.scdn.co/image/ab67616d0000b273828789ff08a16218b2ea9445",
      "width" : 640
    } ],
    "name" : "test",
    "owner" : {
      "display_name" : "myapp",
      "external_urls" : {
        "spotify" : "https://open.spotify.com/user/09k2n3lfgsrjinq164tqkifyb"
      },
      "href" : "https://api.spotify.com/v1/users/09k2n3lfgsrjinq164tqkifyb",
      "id" : "09k2n3lfgsrjinq164tqkifyb",
      "type" : "user",
      "uri" : "spotify:user:09k2n3lfgsrjinq164tqkifyb"
    },
    "primary_color" : null,
    "public" : false,
    "snapshot_id" : "NCw1N2I1ZTcyMjc4N2M1ZmIyZWY0NjZhZWNlZjRhZTczMzgwOTg0M2Q2",
    "tracks" : {
      "href" : "https://api.spotify.com/v1/playlists/0EKAtuGtWTYrDCT8TfrDVP/tracks",
      "total" : 2
    },
    "type" : "playlist",
    "uri" : "spotify:playlist:0EKAtuGtWTYrDCT8TfrDVP"
  }, {
    "collaborative" : false,
    "description" : "",
    "external_urls" : {
      "spotify" : "https://open.spotify.com/playlist/2A7KO4UJl1NxFqmO6b5qDD"
    },
    "href" : "https://api.spotify.com/v1/playlists/2A7KO4UJl1NxFqmO6b5qDD",
    "id" : "2A7KO4UJl1NxFqmO6b5qDD",
    "images" : [ {
      "height" : 640,
      "url" : "https://i.scdn.co/image/ab67616d0000b2732e3049fef96abebf336b7366",
      "width" : 640
    } ],
    "name" : "Test Playlist",
    "owner" : {
      "display_name" : "Henk G",
      "external_urls" : {
        "spotify" : "https://open.spotify.com/user/1119245339"
      },
      "href" : "https://api.spotify.com/v1/users/1119245339",
      "id" : "1119245339",
      "type" : "user",
      "uri" : "spotify:user:1119245339"
    },
    "primary_color" : null,
    "public" : false,
    "snapshot_id" : "Miw1YzY1NDgxZDY0MWQyMmM5ZjFmNjA0YzgwNWM5NTM0NGFjNjA4OGFi",
    "tracks" : {
      "href" : "https://api.spotify.com/v1/playlists/2A7KO4UJl1NxFqmO6b5qDD/tracks",
      "total" : 1
    },
    "type" : "playlist",
    "uri" : "spotify:playlist:2A7KO4UJl1NxFqmO6b5qDD"
  }, {
    "collaborative" : false,
    "description" : "Ontdek vers geselecteerde dance releases! Cover: Tabitha & Sam Feldt",
    "external_urls" : {
      "spotify" : "https://open.spotify.com/playlist/37i9dQZF1DWWrJKwf0q9nn"
    },
    "href" : "https://api.spotify.com/v1/playlists/37i9dQZF1DWWrJKwf0q9nn",
    "id" : "37i9dQZF1DWWrJKwf0q9nn",
    "images" : [ {
      "height" : null,
      "url" : "https://i.scdn.co/image/ab67706f000000039a68f4950d674b726a6a1091",
      "width" : null
    } ],
    "name" : "Hot New Dance",
    "owner" : {
      "display_name" : "Spotify",
      "external_urls" : {
        "spotify" : "https://open.spotify.com/user/spotify"
      },
      "href" : "https://api.spotify.com/v1/users/spotify",
      "id" : "spotify",
      "type" : "user",
      "uri" : "spotify:user:spotify"
    },
    "primary_color" : null,
    "public" : false,
    "snapshot_id" : "MTYwNTg2Mjg2MCwwMDAwMDM3ZjAwMDAwMTc1ZTRlMmE1NDQwMDAwMDE3NWUxM2E0NDdh",
    "tracks" : {
      "href" : "https://api.spotify.com/v1/playlists/37i9dQZF1DWWrJKwf0q9nn/tracks",
      "total" : 77
    },
    "type" : "playlist",
    "uri" : "spotify:playlist:37i9dQZF1DWWrJKwf0q9nn"
  } ],
  "limit" : 50,
  "next" : null,
  "offset" : 50,
  "previous" : "https://api.spotify.com/v1/users/09k2n3lfgsrjinq164tqkifyb/playlists?offset=0&limit=50",
  "total" : 58
}
    at com.adamratzman.spotify.models.serialization.SerializationUtilsKt.parseJson(SerializationUtils.kt:221)
    at com.adamratzman.spotify.models.serialization.SerializationUtilsKt.toPagingObject(SerializationUtils.kt:74)
    at com.adamratzman.spotify.models.AbstractPagingObject.getImpl$spotify_web_api_kotlin$suspendImpl(PagingObjects.kt:444)
    at com.adamratzman.spotify.models.AbstractPagingObject$getImpl$1.invokeSuspend(Unknown Source:12)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
    at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: kotlinx.serialization.json.JsonDecodingException: Unexpected JSON token at offset 13: Expected '{, kind: CLASS'.
 JSON input: {
  "href" : "https://api.spotify.com/v1/us.....
    at kotlinx.serialization.json.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:26)
    at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:311)
    at kotlinx.serialization.json.internal.StreamingJsonInput.beginStructure(StreamingJsonInput.kt:39)
    at com.adamratzman.spotify.models.NullablePagingObject$$serializer.deserialize(Unknown Source:19)
    at com.adamratzman.spotify.models.NullablePagingObject$$serializer.deserialize(PagingObjects.kt:57)
    at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:52)
    at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
    at kotlinx.serialization.builtins.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
    at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:120)
    at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:92)
    at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:54)
    at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:36)
    at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:45)
    at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:52)
    at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
    at kotlinx.serialization.DecodingKt.decode(Decoding.kt:521)
    at kotlinx.serialization.json.Json.parse(Json.kt:131)
    at com.adamratzman.spotify.models.serialization.SerializationUtilsKt$toPagingObject$map$1.invoke(SerializationUtils.kt:76)
    at com.adamratzman.spotify.models.serialization.SerializationUtilsKt$toPagingObject$map$1.invoke(Unknown Source:2)
    at com.adamratzman.spotify.models.serialization.SerializationUtilsKt.parseJson(SerializationUtils.kt:219)
	... 12 more
com.adamratzman.spotify.SpotifyException$ParseException: Unable to parse {
  "href" : "https://api.spotify.com/v1/users/09k2n3lfgsrjinq164tqkifyb/playlists?offset=50&limit=50",
  "items" : [ {
    "collaborative" : false,
    "description" : "",
    "external_urls" : {
      "spotify" : "https://open.spotify.com/playlist/1zd3HCIb7EvzS5ZkD1JHkc"
    },
    "href" : "https://api.spotify.com/v1/playlists/1zd3HCIb7EvzS5ZkD1JHkc",
    "id" : "1zd3HCIb7EvzS5ZkD1JHkc",
    "images" : [ {
      "height" : 640,
      "url" : "https://i.scdn.co/image/ab67616d0000b27311bb04f55be562c76d8e8ecf",
      "width" : 640
    } ],
    "name" : "Don't Give Up",
    "owner" : {
      "display_name" : "myapp",
      "external_urls" : {
        "spotify" : "https://open.spotify.com/user/09k2n3lfgsrjinq164tqkifyb"
      },
      "href" : "https://api.spotify.com/v1/users/09k2n3lfgsrjinq164tqkifyb",
      "id" : "09k2n3lfgsrjinq164tqkifyb",
      "type" : "user",
      "uri" : "spotify:user:09k2n3lfgsrjinq164tqkifyb"
    },
    "primary_color" : null,
    "public" : false,
    "snapshot_id" : "MiwzMTljY2I5YTZhODU3MjY1N2UwMjcwOTc3ZmFlMDAyZTM2ZGVkMjhl",
    "tracks" : {
      "href" : "https://api.spotify.com/v1/playlists/1zd3HCIb7EvzS5ZkD1JHkc/tracks",
      "total" : 1
    },
    "type" : "playlist",
    "uri" : "spotify:playlist:1zd3HCIb7EvzS5ZkD1JHkc"
  }, {
    "collaborative" : false,
    "description" : "",
    "external_urls" : {
      "spotify" : "https://open.spotify.com/playlist/39WGXlIQL7qhOmqyLCHFVj"
    },
    "href" : "https://api.spotify.com/v1/playlists/39WGXlIQL7qhOmqyLCHFVj",
    "id" : "39WGXlIQL7qhOmqyLCHFVj",
    "images" : [ {
      "height" : 640,
      "url" : "https://i.scdn.co/image/ab67616d0000b273edc27582d8f5c3a7c56893bf",
      "width" : 640
    } ],
    "name" : "Right Here Waiting",
    "owner" : {
      "display_name" : "myapp",
      "external_urls" : {
        "spotify" : "https://open.spotify.com/user/09k2n3lfgsrjinq164tqkifyb"
      },
      "href" : "https://api.spotify.com/v1/users/09k2n3lfgsrjinq164tqkifyb",
      "id" : "09k2n3lfgsrjinq164tqkifyb",
      "type" : "user",
      "uri" : "spotify:user:09k2n3lfgsrjinq164tqkifyb"
    },
    "primary_color" : null,
    "public" : false,
    "snapshot_id" : "MixkZjVjYjc3NTBhZTdjOTJmMTcyMGFhOWRiZWEyNTk4NWIzYWU0ZmZi",
    "tracks" : {
      "href" : "https://api.spotify.com/v1/playlists/39WGXlIQL7qhOmqyLCHFVj/tracks",
      "total" : 1
    },
    "type" : "playlist",
    "uri" : "spotify:playlist:39WGXlIQL7qhOmqyLCHFVj"
  }, {
    "collaborative" : false,
    "description" : "",
    "external_urls" : {
      "spotify" : "https://open.spotify.com/playlist/0RiKL1FLSnrt1ZkUqFdiNQ"
    },
    "href" : "https://api.spotify.com/v1/playlists/0RiKL1FLSnrt1ZkUqFdiNQ",
    "id" : "0RiKL1FLSnrt1ZkUqFdiNQ",
    "images" : [ {
      "height" : 640,
      "url" : "https://i.scdn.co/image/ab67616d0000b273cc57e9b00b87dd0f6e868347",
      "width" : 640
    } ],
    "name" : "Where Do Broken Hearts Go",
    "owner" : {
      "display_name" : "myapp",
      "external_urls" : {
        "spotify" : "https://open.spotify.com/user/09k2n3lfgsrjinq164tqkifyb"
      },
      "href" : "https://api.spotify.com/v1/users/09k2n3lfgsrjinq164tqkifyb",
      "id" : "09k2n3lfgsrjinq164tqkifyb",
      "type" : "user",
      "uri" : "spotify:user:09k2n3lfgsrjinq164tqkifyb"
    },
    "primary_color" : null,
    "public" : false,
    "snapshot_id" : "MixhMWNiNTQ4YzBjOTgyMWY2ZDA3NjBiMzg2ZDI4ZDE4ZjM4MmEzZTMz",
    "tracks" : {
      "href" : "https://api.spotify.com/v1/playlists/0RiKL1FLSnrt1ZkUqFdiNQ/tracks",
      "total" : 1
    },
    "type" : "playlist",
    "uri" : "spotify:playlist:0RiKL1FLSnrt1ZkUqFdiNQ"
  }, {
    "collaborative" : false,
    "description" : "",
    "external_urls" : {
      "spotify" : "https://open.spotify.com/playlist/4cyi1JBHsmml1DoRY8oTUJ"
    },
    "href" : "https://api.spotify.com/v1/playlists/4cyi1JBHsmml1DoRY8oTUJ",
    "id" : "4cyi1JBHsmml1DoRY8oTUJ",
    "images" : [ {
      "height" : 640,
      "url" : "https://i.scdn.co/image/ab67616d0000b27313018b9c71e6bfc1bdf02d92",
      "width" : 640
    } ],
    "name" : "Breaking Hearts (Ain't What It Used To Be)",
    "owner" : {
      "display_name" : "myapp",
      "external_urls" : {
        "spotify" : "https://open.spotify.com/user/09k2n3lfgsrjinq164tqkifyb"
      },
      "href" : "https://api.spotify.com/v1/users/09k2n3lfgsrjinq164tqkifyb",
      "id" : "09k2n3lfgsrjinq164tqkifyb",
      "type" : "user",
      "uri" : "spotify:user:09k2n3lfgsrjinq164tqkifyb"
    },
    "primary_color" : null,
    "public" : false,
    "snapshot_id" : "MixjNGQ3MDI1YWE2NTExMjRkMzNmYjFhNDNhMDYzNjkwOWEwZDYxM2Jj",
    "tracks" : {
      "href" : "https://api.spotify.com/v1/playlists/4cyi1JBHsmml1DoRY8oTUJ/tracks",
      "total" : 1
    },
    "type" : "playlist",
    "uri" : "spotify:playlist:4cyi1JBHsmml1DoRY8oTUJ"
  }, {
    "collaborative" : false,
    "description" : "",
    "external_urls" : {
      "spotify" : "https://open.spotify.com/playlist/15JNQSdsuQwfs64azeXag4"
    },
    "href" : "https://api.spotify.com/v1/playlists/15JNQSdsuQwfs64azeXag4",
    "id" : "15JNQSdsuQwfs64azeXag4",
    "images" : [ {
      "height" : 640,
      "url" : "https://i.scdn.co/image/ab67616d0000b27342678f54dfd1d5afb3eea19a",
      "width" : 640
    } ],
    "name" : "Slipping Through My Fingers",
    "owner" : {
      "display_name" : "myapp",
      "external_urls" : {
        "spotify" : "https://open.spotify.com/user/09k2n3lfgsrjinq164tqkifyb"
      },
      "href" : "https://api.spotify.com/v1/users/09k2n3lfgsrjinq164tqkifyb",
      "id" : "09k2n3lfgsrjinq164tqkifyb",
      "type" : "user",
      "uri" : "spotify:user:09k2n3lfgsrjinq164tqkifyb"
    },
    "primary_color" : null,
    "public" : false,
    "snapshot_id" : "MixmN2E3NjE5YzljNTA5ZDQ5ODczNmU5YTdjOWU4Y2U0NTA1MjI1ODU2",
    "tracks" : {
      "href" : "https://api.spotify.com/v1/playlists/15JNQSdsuQwfs64azeXag4/tracks",
      "total" : 1
    },
    "type" : "playlist",
    "uri" : "spotify:playlist:15JNQSdsuQwfs64azeXag4"
  }, {
    "collaborative" : false,
    "description" : "",
    "external_urls" : {
      "spotify" : "https://open.spotify.com/playlist/0EKAtuGtWTYrDCT8TfrDVP"
    },
    "href" : "https://api.spotify.com/v1/playlists/0EKAtuGtWTYrDCT8TfrDVP",
    "id" : "0EKAtuGtWTYrDCT8TfrDVP",
    "images" : [ {
      "height" : 640,
      "url" : "https://i.scdn.co/image/ab67616d0000b273828789ff08a16218b2ea9445",
      "width" : 640
    } ],
    "name" : "test",
    "owner" : {
      "display_name" : "myapp",
      "external_urls" : {
        "spotify" : "https://open.spotify.com/user/09k2n3lfgsrjinq164tqkifyb"
      },
      "href" : "https://api.spotify.com/v1/users/09k2n3lfgsrjinq164tqkifyb",
      "id" : "09k2n3lfgsrjinq164tqkifyb",
      "type" : "user",
      "uri" : "spotify:user:09k2n3lfgsrjinq164tqkifyb"
    },
    "primary_color" : null,
    "public" : false,
    "snapshot_id" : "NCw1N2I1ZTcyMjc4N2M1ZmIyZWY0NjZhZWNlZjRhZTczMzgwOTg0M2Q2",
    "tracks" : {
      "href" : "https://api.spotify.com/v1/playlists/0EKAtuGtWTYrDCT8TfrDVP/tracks",
      "total" : 2
    },
    "type" : "playlist",
    "uri" : "spotify:playlist:0EKAtuGtWTYrDCT8TfrDVP"
  }, {
    "collaborative" : false,
    "description" : "",
    "external_urls" : {
      "spotify" : "https://open.spotify.com/playlist/2A7KO4UJl1NxFqmO6b5qDD"
    },
    "href" : "https://api.spotify.com/v1/playlists/2A7KO4UJl1NxFqmO6b5qDD",
    "id" : "2A7KO4UJl1NxFqmO6b5qDD",
    "images" : [ {
      "height" : 640,
      "url" : "https://i.scdn.co/image/ab67616d0000b2732e3049fef96abebf336b7366",
      "width" : 640
    } ],
    "name" : "Test Playlist",
    "owner" : {
      "display_name" : "dkasf ldskaf",
      "external_urls" : {
        "spotify" : "https://open.spotify.com/user/435353434"
      },
      "href" : "https://api.spotify.com/v1/users/435353434",
      "id" : "435353434",
      "type" : "user",
      "uri" : "spotify:user:435353434"
    },
    "primary_color" : null,
    "public" : false,
    "snapshot_id" : "Miw1YzY1NDgxZDY0MWQyMmM5ZjFmNjA0YzgwNWM5NTM0NGFjNjA4OGFi",
    "tracks" : {
      "href" : "https://api.spotify.com/v1/playlists/2A7KO4UJl1NxFqmO6b5qDD/tracks",
      "total" : 1
    },
    "type" : "playlist",
    "uri" : "spotify:playlist:2A7KO4UJA93DFqmO6b5qDD"
  }, {
    "collaborative" : false,
    "description" : "Ontdek vers geselecteerde dance releases! Cover: Tabitha & Sam Feldt",
    "external_urls" : {
      "spotify" : "https://open.spotify.com/playlist/37i9dQZF1DWWrJKwf0q9nn"
    },
    "href" : "https://api.spotify.com/v1/playlists/37i9dQZF1DWWrJKwf0q9nn",
    "id" : "37i9dQZF1DWWrJKwf0q9nn",
    "images" : [ {
      "height" : null,
      "url" : "https://i.scdn.co/image/ab67706f000000039a68f4950d674b726a6a1091",
      "width" : null
    } ],
    "name" : "Hot New Dance",
    "owner" : {
      "display_name" : "Spotify",
      "external_urls" : {
        "spotify" : "https://open.spotify.com/user/spotify"
      },
      "href" : "https://api.spotify.com/v1/users/spotify",
      "id" : "spotify",
      "type" : "user",
      "uri" : "spotify:user:spotify"
    },
    "primary_color" : null,
    "public" : false,
    "snapshot_id" : "MTYwNTg2Mjg2MCwwMDAwMDM3ZjAwMDAwMTc1ZTRlMmE1NDQwMDAwMDE3NWUxM2E0NDdh",
    "tracks" : {
      "href" : "https://api.spotify.com/v1/playlists/37i9dQZF1DWWrJKwf0q9nn/tracks",
      "total" : 77
    },
    "type" : "playlist",
    "uri" : "spotify:playlist:37i9dQZF1DWWrJKwf0q9nn"
  } ],
  "limit" : 50,
  "next" : null,
  "offset" : 50,
  "previous" : "https://api.spotify.com/v1/users/09k2n3lfgsrjinq164tqkifyb/playlists?offset=0&limit=50",
  "total" : 58
}
    at com.adamratzman.spotify.models.serialization.SerializationUtilsKt.parseJson(SerializationUtils.kt:221)
    at com.adamratzman.spotify.models.serialization.SerializationUtilsKt.toPagingObject(SerializationUtils.kt:74)
    at com.adamratzman.spotify.models.AbstractPagingObject.getImpl$spotify_web_api_kotlin$suspendImpl(PagingObjects.kt:444)
    at com.adamratzman.spotify.models.AbstractPagingObject$getImpl$1.invokeSuspend(Unknown Source:12)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
    at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: kotlinx.serialization.json.JsonDecodingException: Unexpected JSON token at offset 13: Expected '{, kind: CLASS'.
 JSON input: {
  "href" : "https://api.spotify.com/v1/us.....
    at kotlinx.serialization.json.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:26)
    at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:311)
    at kotlinx.serialization.json.internal.StreamingJsonInput.beginStructure(StreamingJsonInput.kt:39)
    at com.adamratzman.spotify.models.NullablePagingObject$$serializer.deserialize(Unknown Source:19)
    at com.adamratzman.spotify.models.NullablePagingObject$$serializer.deserialize(PagingObjects.kt:57)
    at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:52)
    at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
    at kotlinx.serialization.builtins.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
    at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:120)
    at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:92)
    at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:54)
    at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:36)
    at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:45)
    at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:52)
    at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
    at kotlinx.serialization.DecodingKt.decode(Decoding.kt:521)
    at kotlinx.serialization.json.Json.parse(Json.kt:131)
    at com.adamratzman.spotify.models.serialization.SerializationUtilsKt$toPagingObject$map$1.invoke(SerializationUtils.kt:76)
    at com.adamratzman.spotify.models.serialization.SerializationUtilsKt$toPagingObject$map$1.invoke(Unknown Source:2)
    at com.adamratzman.spotify.models.serialization.SerializationUtilsKt.parseJson(SerializationUtils.kt:219)
	... 12 more
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge Chromium
 - Version: Latest

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10 (and emulators)
 - OS: Android 10
 - Browser: Chrome
 - Version: Latest

**Additional context**
I was using library version 3.2.14

**Comment by adamint** [comment]
I am able to reproduce this on 3.3.0.

**Comment by adamint** [comment]
The above commit resolves this issue by removing the innerObjectName from the remaining three classes that still had one in Paging Object deserialization. 3.3.01 is syncing and should be available in a couple hours. This issue will be closed then.
